---
- name: install packages
  shell: "{{ nvm_install_shell }} -lc nvm use {{ item.0 }} && npm install -g {{ item.1 }}"
  with_nested:
    - "{{ nvm_node_versions }}"
    - "{{ nvm_global_packages }}"
